name: Pull Request CI

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout latest code
              uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Run yarn
              run: yarn
            - name: Run tests
              uses: tangro/actions-test@1.1.1
              # with:
              #     post-comment: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_CONTEXT: ${{ toJson(github) }}
